- name: Launch EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Launch a new EC2 instance
      amazon.aws.ec2_instance:
        name: MyEC2Server
        key_name: my-keypair
        instance_type: t2.micro
        image_id: ami-0abcdef1234567890
        region: us-east-1
        wait: yes
        count: 1
        network:
          assign_public_ip: yes
        tags:
          Environment: Dev
